[tool.poetry]
name = "nonebot-adapter-mirai"
version = "2.0.0-alpha.16"
description = "Mirai Api HTTP adapter for nonebot2"
authors = ["Mix <admin@yami.im>", "yanyongyu <yyy@nonebot.dev>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
homepage = "https://v2.nonebot.dev/"
repository = "https://github.com/nonebot/adapter-mirai"
documentation = "https://v2.nonebot.dev/"
keywords = ["bot", "qq", "qqbot", "mirai"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
packages = [
  { include = "nonebot" }
]
exclude = ["nonebot/__init__.py", "nonebot/adapters/__init__.py"]

[tool.poetry.dependencies]
python = "^3.7.3"
httpx = ">=0.20.0, <1.0.0"
nonebot2 = "^2.0.0-alpha.14"

[tool.poetry.dev-dependencies]
nonebot2 = { git = "https://github.com/nonebot/nonebot2.git", branch = "dev" }

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[tool.black]
line-length = 88
target-version = ["py37", "py38", "py39"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 80
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
